def create_bird_index_list():
	bird_index_list = {"Abert's Towhee Bird": 0,
         "Acorn Woodpecker Bird": 1,
         "Allen's Hummingbird Bird": 2,
         "American Avocet Bird": 3,
         "American Bittern Bird": 4,
         "American Coot Bird": 5,
         "American Crow Bird": 6,
         "American Dipper Bird": 7,
         "American Golden-Plover Bird": 8,
         "American Goldfinch Bird": 9,
         "American Goshawk Bird": 10,
         "American Kestrel Bird": 11,
         "American Oystercatcher Bird": 12,
         "American Pipit Bird": 13,
         "American Redstart Bird": 14,
         "American Robin Bird": 15,
         "American Tree Sparrow Bird": 16,
         "American White Pelican Bird": 17,
         "American Wigeon Bird": 18,
         "Ancient Murrelet Bird": 19,
         "Anhinga Bird": 20,
         "Anna's Hummingbird Bird": 21,
         "Arctic Tern Bird": 22,
         "Ash-throated Flycatcher Bird": 23,
         "Ashy Storm-Petrel Bird": 24,
         "Baird's Sandpiper Bird": 25,
         "Baird's Sparrow Bird": 26,
         "Bald Eagle Bird": 27,
         "Baltimore Oriole Bird": 28,
         "Band-tailed Pigeon Bird": 29,
         "Bank Swallow Bird": 30,
         "Bar-tailed Godwit Bird": 31,
         "Barn Owl Bird": 32,
         "Barn Swallow Bird": 33,
         "Bay-breasted Warbler Bird": 34,
         "Belcher's Gull Bird": 35,
         "Bell's Sparrow Bird": 36,
         "Bell's Vireo Bird": 37,
         "Belted Kingfisher Bird": 38,
         "Bendire's Thrasher Bird": 39,
         "Bewick's Wren Bird": 40,
         "Black Oystercatcher Bird": 41,
         "Black Phoebe Bird": 42,
         "Black Rail Bird": 43,
         "Black Scoter Bird": 44,
         "Black Skimmer Bird": 45,
         "Black Storm-Petrel Bird": 46,
         "Black Swift Bird": 47,
         "Black Tern Bird": 48,
         "Black Turnstone Bird": 49,
         "Black Vulture Bird": 50,
         "Black-and-white Warbler Bird": 51,
         "Black-backed Oriole Bird": 52,
         "Black-bellied Plover Bird": 53,
         "Black-chinned Hummingbird Bird": 54,
         "Black-chinned Sparrow Bird": 55,
         "Black-crowned Night Heron Bird": 56,
         "Black-footed Albatross Bird": 57,
         "Black-headed Grosbeak Bird": 58,
         "Black-headed Gull Bird": 59,
         "Black-legged Kittiwake Bird": 60,
         "Black-necked Stilt Bird": 61,
         "Black-tailed Gnatcatcher Bird": 62,
         "Black-tailed Gull Bird": 63,
         "Black-throated Blue Warbler Bird": 64,
         "Black-throated Gray Warbler Bird": 65,
         "Black-throated Green Warbler Bird": 66,
         "Black-throated Magpie-Jay Bird": 67,
         "Black-throated Sparrow Bird": 68,
         "Black-vented Shearwater Bird": 69,
         "Blackburnian Warbler Bird": 70,
         "Blackpoll Warbler Bird": 71,
         "Blue Grosbeak Bird": 72,
         "Blue-footed Booby Bird": 73,
         "Blue-gray Gnatcatcher Bird": 74,
         "Blue-headed Vireo Bird": 75,
         "Blue-throated Mountain-gem Bird": 76,
         "Blue-winged Teal Bird": 77,
         "Blue-winged Warbler Bird": 78,
         "Bobolink Bird": 79,
         "Bohemian Waxwing Bird": 80,
         "Bonaparte's Gull Bird": 81,
         "Brandt's Cormorant Bird": 82,
         "Brant Bird": 83,
         "Brewer's Blackbird Bird": 84,
         "Brewer's Sparrow Bird": 85,
         "Bridled Tern Bird": 86,
         "Broad-billed Hummingbird Bird": 87,
         "Broad-tailed Hummingbird Bird": 88,
         "Broad-winged Hawk Bird": 89,
         "Bronzed Cowbird Bird": 90,
         "Brown Booby Bird": 91,
         "Brown Creeper Bird": 92,
         "Brown Pelican Bird": 93,
         "Brown Thrasher Bird": 94,
         "Brown-crested Flycatcher Bird": 95,
         "Brown-headed Cowbird Bird": 96,
         "Buff-breasted Sandpiper Bird": 97,
         "Bufflehead Bird": 98,
         "Buller's Shearwater Bird": 99,
         "Bullock's Oriole Bird": 100,
         "Burrowing Owl Bird": 101,
         "Bushtit Bird": 102,
         "Cackling Goose Bird": 103,
         "Cactus Wren Bird": 104,
         "California Condor Bird": 105,
         "California Gnatcatcher Bird": 106,
         "California Gull Bird": 107,
         "California Quail Bird": 108,
         "California Scrub-Jay Bird": 109,
         "California Thrasher Bird": 110,
         "California Towhee Bird": 111,
         "Calliope Hummingbird Bird": 112,
         "Canada Goose Bird": 113,
         "Canada Warbler Bird": 114,
         "Canvasback Bird": 115,
         "Canyon Wren Bird": 116,
         "Cape May Warbler Bird": 117,
         "Caspian Tern Bird": 118,
         "Cassin's Auklet Bird": 119,
         "Cassin's Finch Bird": 120,
         "Cassin's Kingbird Bird": 121,
         "Cassin's Sparrow Bird": 122,
         "Cassin's Vireo Bird": 123,
         "Cedar Waxwing Bird": 124,
         "Cerulean Warbler Bird": 125,
         "Chestnut-collared Longspur Bird": 126,
         "Chestnut-sided Warbler Bird": 127,
         "Chimney Swift Bird": 128,
         "Chipping Sparrow Bird": 129,
         "Cinnamon Teal Bird": 130,
         "Cinnamon-rumped Seedeater Bird": 131,
         "Clark's Grebe Bird": 132,
         "Clark's Nutcracker Bird": 133,
         "Clay-colored Sparrow Bird": 134,
         "Cliff Swallow Bird": 135,
         "Common Black Hawk Bird": 136,
         "Common Gallinule Bird": 137,
         "Common Goldeneye Bird": 138,
         "Common Grackle Bird": 139,
         "Common Ground Dove Bird": 140,
         "Common Loon Bird": 141,
         "Common Merganser Bird": 142,
         "Common Murre Bird": 143,
         "Common Nighthawk Bird": 144,
         "Common Poorwill Bird": 145,
         "Common Raven Bird": 146,
         "Common Redpoll Bird": 147,
         "Common Tern Bird": 148,
         "Common Yellowthroat Bird": 149,
         "Connecticut Warbler Bird": 150,
         "Cook's Petrel Bird": 151,
         "Cooper's Hawk Bird": 152,
         "Cory's Shearwater Bird": 153,
         "Costa's Hummingbird Bird": 154,
         "Craveri's Murrelet Bird": 155,
         "Crested Caracara Bird": 156,
         "Crissal Thrasher Bird": 157,
         "Curlew Sandpiper Bird": 158,
         "Curve-billed Thrasher Bird": 159,
         "Dark-eyed Junco Bird": 160,
         "Dickcissel Bird": 161,
         "Double-crested Cormorant Bird": 162,
         "Downy Woodpecker Bird": 163,
         "Dunlin Bird": 164,
         "Dusky Flycatcher Bird": 165,
         "Dusky Warbler Bird": 166,
         "Dusky-capped Flycatcher Bird": 167,
         "Eared Grebe Bird": 168,
         "Eastern Kingbird Bird": 169,
         "Eastern Phoebe Bird": 170,
         "Eastern Towhee Bird": 171,
         "Eastern Whip-poor-will Bird": 172,
         "Eastern Wood-Pewee Bird": 173,
         "Elegant Tern Bird": 174,
         "Eurasian Collared-Dove Bird": 175,
         "Eurasian Wigeon Bird": 176,
         "European Starling Bird": 177,
         "Evening Grosbeak Bird": 178,
         "Ferruginous Hawk Bird": 179,
         "Flammulated Owl Bird": 180,
         "Flesh-footed Shearwater Bird": 181,
         "Fork-tailed Storm-Petrel Bird": 182,
         "Forster's Tern Bird": 183,
         "Fox Sparrow Bird": 184,
         "Franklin's Gull Bird": 185,
         "Fulvous Whistling-Duck Bird": 186,
         "Gadwall Bird": 187,
         "Gambel's Quail Bird": 188,
         "Gila Woodpecker Bird": 189,
         "Glaucous Gull Bird": 190,
         "Glaucous-winged Gull Bird": 191,
         "Glossy Ibis Bird": 192,
         "Golden Eagle Bird": 193,
         "Golden-crowned Kinglet Bird": 194,
         "Golden-crowned Sparrow Bird": 195,
         "Golden-winged Warbler Bird": 196,
         "Grace's Warbler Bird": 197,
         "Grasshopper Sparrow Bird": 198,
         "Gray Catbird Bird": 199,
         "Gray Flycatcher Bird": 200,
         "Gray Silky-flycatcher Bird": 201,
         "Gray Thrasher Bird": 202,
         "Gray Vireo Bird": 203,
         "Gray-cheeked Thrush Bird": 204,
         "Gray-faced Petrel Bird": 205,
         "Gray-tailed Tattler Bird": 206,
         "Great Blue Heron Bird": 207,
         "Great Crested Flycatcher Bird": 208,
         "Great Egret Bird": 209,
         "Great Horned Owl Bird": 210,
         "Great Shearwater Bird": 211,
         "Great-tailed Grackle Bird": 212,
         "Greater Pewee Bird": 213,
         "Greater Roadrunner Bird": 214,
         "Greater Scaup Bird": 215,
         "Greater White-fronted Goose Bird": 216,
         "Greater Yellowlegs Bird": 217,
         "Green Heron Bird": 218,
         "Green-tailed Towhee Bird": 219,
         "Green-winged Teal Bird": 220,
         "Groove-billed Ani Bird": 221,
         "Guadalupe Murrelet Bird": 222,
         "Gull-billed Tern Bird": 223,
         "Hairy Woodpecker Bird": 224,
         "Hammond's Flycatcher Bird": 225,
         "Harlequin Duck Bird": 226,
         "Harris's Hawk Bird": 227,
         "Harris's Sparrow Bird": 228,
         "Heermann's Gull Bird": 229,
         "Hepatic Tanager Bird": 230,
         "Hermit Thrush Bird": 231,
         "Hermit Warbler Bird": 232,
         "Herring Gull Bird": 233,
         "Hooded Merganser Bird": 234,
         "Hooded Oriole Bird": 235,
         "Hooded Warbler Bird": 236,
         "Horned Grebe Bird": 237,
         "Horned Lark Bird": 238,
         "Horned Puffin Bird": 239,
         "House Finch Bird": 240,
         "House Sparrow Bird": 241,
         "House Wren Bird": 242,
         "Hudsonian Godwit Bird": 243,
         "Hutton's Vireo Bird": 244,
         "Iceland Gull Bird": 245,
         "Inca Dove Bird": 246,
         "Indigo Bunting Bird": 247,
         "Kentucky Warbler Bird": 248,
         "Killdeer Bird": 249,
         "King Eider Bird": 250,
         "Kittlitz's Murrelet Bird": 251,
         "Ladder-backed Woodpecker Bird": 252,
         "Lapland Longspur Bird": 253,
         "Lark Bunting Bird": 254,
         "Lark Sparrow Bird": 255,
         "Laughing Gull Bird": 256,
         "Lawrence's Goldfinch Bird": 257,
         "Laysan Albatross Bird": 258,
         "Lazuli Bunting Bird": 259,
         "LeConte's Sparrow Bird": 260,
         "LeConte's Thrasher Bird": 261,
         "Leach's Storm-Petrel Bird": 262,
         "Least Bittern Bird": 263,
         "Least Flycatcher Bird": 264,
         "Least Sandpiper Bird": 265,
         "Least Storm-Petrel Bird": 266,
         "Least Tern Bird": 267,
         "Lesser Black-backed Gull Bird": 268,
         "Lesser Goldfinch Bird": 269,
         "Lesser Nighthawk Bird": 270,
         "Lesser Scaup Bird": 271,
         "Lesser Yellowlegs Bird": 272,
         "Lewis's Woodpecker Bird": 273,
         "Lilac-crowned Parrot Bird": 274,
         "Lincoln's Sparrow Bird": 275,
         "Little Blue Heron Bird": 276,
         "Little Bunting Bird": 277,
         "Little Gull Bird": 278,
         "Little Stint Bird": 279,
         "Loggerhead Shrike Bird": 280,
         "Long-billed Curlew Bird": 281,
         "Long-billed Dowitcher Bird": 282,
         "Long-eared Owl Bird": 283,
         "Long-tailed Duck Bird": 284,
         "Long-tailed Jaeger Bird": 285,
         "Louisiana Waterthrush Bird": 286,
         "Lucy's Warbler Bird": 287,
         "MacGillivray's Warbler Bird": 288,
         "Magnificent Frigatebird Bird": 289,
         "Magnolia Warbler Bird": 290,
         "Mallard Bird": 291,
         "Mandarin Duck Bird": 292,
         "Manx Shearwater Bird": 293,
         "Marbled Godwit Bird": 294,
         "Marbled Murrelet Bird": 295,
         "Marsh Wren Bird": 296,
         "Masked Booby Bird": 297,
         "Merlin Bird": 298,
         "Mexican Duck Bird": 299,
         "Mexican Whip-poor-will Bird": 300,
         "Mississippi Kite Bird": 301,
         "Mitred Parakeet Bird": 302,
         "Monk Parakeet Bird": 303,
         "Mottled Petrel Bird": 304,
         "Mountain Bluebird Bird": 305,
         "Mountain Chickadee Bird": 306,
         "Mountain Plover Bird": 307,
         "Mountain Quail Bird": 308,
         "Mourning Dove Bird": 309,
         "Mourning Warbler Bird": 310,
         "Nashville Warbler Bird": 311,
         "Nazca Booby Bird": 312,
         "Nelson's Sparrow Bird": 313,
         "Neotropic Cormorant Bird": 314,
         "Newell's Shearwater Bird": 315,
         "Northern Flicker Bird": 316,
         "Northern Fulmar Bird": 317,
         "Northern Harrier Bird": 318,
         "Northern Mockingbird Bird": 319,
         "Northern Parula Bird": 320,
         "Northern Pintail Bird": 321,
         "Northern Pygmy-Owl Bird": 322,
         "Northern Red Bishop Bird": 323,
         "Northern Rough-winged Swallow Bird": 324,
         "Northern Saw-whet Owl Bird": 325,
         "Northern Shoveler Bird": 326,
         "Northern Waterthrush Bird": 327,
         "Northern Wheatear Bird": 328,
         "Nuttall's Woodpecker Bird": 329,
         "Oak Titmouse Bird": 330,
         "Olive-sided Flycatcher Bird": 331,
         "Orange-crowned Warbler Bird": 332,
         "Orchard Oriole Bird": 333,
         "Osprey Bird": 334,
         "Ovenbird Bird": 335,
         "Pacific Golden-Plover Bird": 336,
         "Pacific Loon Bird": 337,
         "Pacific Wren Bird": 338,
         "Painted Bunting Bird": 339,
         "Painted Redstart Bird": 340,
         "Palm Warbler Bird": 341,
         "Parakeet Auklet Bird": 342,
         "Parasitic Jaeger Bird": 343,
         "Pectoral Sandpiper Bird": 344,
         "Pelagic Cormorant Bird": 345,
         "Peregrine Falcon Bird": 346,
         "Phainopepla Bird": 347,
         "Philadelphia Vireo Bird": 348,
         "Pied-billed Grebe Bird": 349,
         "Pigeon Guillemot Bird": 350,
         "Pine Siskin Bird": 351,
         "Pine Warbler Bird": 352,
         "Pink-footed Shearwater Bird": 353,
         "Pinyon Jay Bird": 354,
         "Plumbeous Vireo Bird": 355,
         "Pomarine Jaeger Bird": 356,
         "Prairie Falcon Bird": 357,
         "Prairie Warbler Bird": 358,
         "Prothonotary Warbler Bird": 359,
         "Purple Finch Bird": 360,
         "Purple Gallinule Bird": 361,
         "Purple Martin Bird": 362,
         "Pygmy Nuthatch Bird": 363,
         "Pyrrhuloxia Bird": 364,
         "Red Crossbill Bird": 365,
         "Red Knot Bird": 366,
         "Red Phalarope Bird": 367,
         "Red-billed Tropicbird Bird": 368,
         "Red-breasted Merganser Bird": 369,
         "Red-breasted Nuthatch Bird": 370,
         "Red-breasted Sapsucker Bird": 371,
         "Red-crowned Parrot Bird": 372,
         "Red-eyed Vireo Bird": 373,
         "Red-faced Warbler Bird": 374,
         "Red-footed Booby Bird": 375,
         "Red-lored Parrot Bird": 376,
         "Red-masked Parakeet Bird": 377,
         "Red-naped Sapsucker Bird": 378,
         "Red-necked Grebe Bird": 379,
         "Red-necked Phalarope Bird": 380,
         "Red-necked Stint Bird": 381,
         "Red-shouldered Hawk Bird": 382,
         "Red-tailed Hawk Bird": 383,
         "Red-tailed Tropicbird Bird": 384,
         "Red-throated Loon Bird": 385,
         "Red-throated Pipit Bird": 386,
         "Red-whiskered Bulbul Bird": 387,
         "Red-winged Blackbird Bird": 388,
         "Reddish Egret Bird": 389,
         "Redhead Bird": 390,
         "Rhinoceros Auklet Bird": 391,
         "Ridgway's Rail Bird": 392,
         "Ring-billed Gull Bird": 393,
         "Ring-necked Duck Bird": 394,
         "Ring-necked Pheasant Bird": 395,
         "Rivoli's Hummingbird Bird": 396,
         "Rock Pigeon Bird": 397,
         "Rock Wren Bird": 398,
         "Rose-breasted Grosbeak Bird": 399,
         "Rose-ringed Parakeet Bird": 400,
         "Roseate Spoonbill Bird": 401,
         "Ross's Goose Bird": 402,
         "Rough-legged Hawk Bird": 403,
         "Royal Tern Bird": 404,
         "Ruby-crowned Kinglet Bird": 405,
         "Ruddy Duck Bird": 406,
         "Ruddy Ground Dove Bird": 407,
         "Ruddy Turnstone Bird": 408,
         "Ruff Bird": 409,
         "Rufous Hummingbird Bird": 410,
         "Rufous-backed Robin Bird": 411,
         "Rufous-crowned Sparrow Bird": 412,
         "Rusty Blackbird Bird": 413,
         "Sabine's Gull Bird": 414,
         "Sage Thrasher Bird": 415,
         "Sagebrush Sparrow Bird": 416,
         "Sanderling Bird": 417,
         "Sandhill Crane Bird": 418,
         "Sandwich Tern Bird": 419,
         "Savannah Sparrow Bird": 420,
         "Say's Phoebe Bird": 421,
         "Scaly-breasted Munia Bird": 422,
         "Scarlet Tanager Bird": 423,
         "Scissor-tailed Flycatcher Bird": 424,
         "Scott's Oriole Bird": 425,
         "Scripps's Murrelet Bird": 426,
         "Semipalmated Plover Bird": 427,
         "Semipalmated Sandpiper Bird": 428,
         "Sharp-shinned Hawk Bird": 429,
         "Sharp-tailed Sandpiper Bird": 430,
         "Short-billed Dowitcher Bird": 431,
         "Short-billed Gull Bird": 432,
         "Short-eared Owl Bird": 433,
         "Short-tailed Albatross Bird": 434,
         "Short-tailed Shearwater Bird": 435,
         "Siberian Sand-Plover Bird": 436,
         "Slaty-backed Gull Bird": 437,
         "Snow Bunting Bird": 438,
         "Snow Goose Bird": 439,
         "Snowy Egret Bird": 440,
         "Snowy Plover Bird": 441,
         "Solitary Sandpiper Bird": 442,
         "Song Sparrow Bird": 443,
         "Sooty Shearwater Bird": 444,
         "Sooty Tern Bird": 445,
         "Sora Bird": 446,
         "South Polar Skua Bird": 447,
         "Spotted Dove Bird": 448,
         "Spotted Owl Bird": 449,
         "Spotted Redshank Bird": 450,
         "Spotted Sandpiper Bird": 451,
         "Spotted Towhee Bird": 452,
         "Sprague's Pipit Bird": 453,
         "Stejneger's Petrel Bird": 454,
         "Steller's Jay Bird": 455,
         "Stilt Sandpiper Bird": 456,
         "Streak-backed Oriole Bird": 457,
         "Streaked Shearwater Bird": 458,
         "Sulphur-bellied Flycatcher Bird": 459,
         "Summer Tanager Bird": 460,
         "Surf Scoter Bird": 461,
         "Surfbird Bird": 462,
         "Swainson's Hawk Bird": 463,
         "Swainson's Thrush Bird": 464,
         "Swallow-tailed Gull Bird": 465,
         "Swallow-tailed Kite Bird": 466,
         "Swamp Sparrow Bird": 467,
         "Swinhoe's White-eye Bird": 468,
         "Tennessee Warbler Bird": 469,
         "Thick-billed Kingbird Bird": 470,
         "Thick-billed Longspur Bird": 471,
         "Townsend's Solitaire Bird": 472,
         "Townsend's Storm-Petrel Bird": 473,
         "Townsend's Warbler Bird": 474,
         "Tree Swallow Bird": 475,
         "Tricolored Blackbird Bird": 476,
         "Tricolored Heron Bird": 477,
         "Tropical Kingbird Bird": 478,
         "Tufted Duck Bird": 479,
         "Tufted Puffin Bird": 480,
         "Tundra Swan Bird": 481,
         "Turkey Vulture Bird": 482,
         "Upland Sandpiper Bird": 483,
         "Varied Bunting Bird": 484,
         "Varied Thrush Bird": 485,
         "Vaux's Swift Bird": 486,
         "Verdin Bird": 487,
         "Vermilion Flycatcher Bird": 488,
         "Vesper Sparrow Bird": 489,
         "Violet-crowned Hummingbird Bird": 490,
         "Violet-green Swallow Bird": 491,
         "Virginia Rail Bird": 492,
         "Virginia's Warbler Bird": 493,
         "Wandering Tattler Bird": 494,
         "Warbling Vireo Bird": 495,
         "Warbling White-eye Bird": 496,
         "Wedge-rumped Storm-Petrel Bird": 497,
         "Wedge-tailed Shearwater Bird": 498,
         "Western Bluebird Bird": 499,
         "Western Cattle Egret Bird": 500,
         "Western Flycatcher Bird": 501,
         "Western Grebe Bird": 502,
         "Western Gull Bird": 503,
         "Western Kingbird Bird": 504,
         "Western Meadowlark Bird": 505,
         "Western Sandpiper Bird": 506,
         "Western Screech-Owl Bird": 507,
         "Western Tanager Bird": 508,
         "Western Wood-Pewee Bird": 509,
         "Whimbrel Bird": 510,
         "White Ibis Bird": 511,
         "White Wagtail Bird": 512,
         "White-breasted Nuthatch Bird": 513,
         "White-crowned Sparrow Bird": 514,
         "White-eyed Vireo Bird": 515,
         "White-faced Ibis Bird": 516,
         "White-headed Woodpecker Bird": 517,
         "White-tailed Kite Bird": 518,
         "White-throated Sparrow Bird": 519,
         "White-throated Swift Bird": 520,
         "White-winged Dove Bird": 521,
         "White-winged Scoter Bird": 522,
         "Wild Turkey Bird": 523,
         "Willet Bird": 524,
         "Williamson's Sapsucker Bird": 525,
         "Willow Flycatcher Bird": 526,
         "Wilson's Phalarope Bird": 527,
         "Wilson's Plover Bird": 528,
         "Wilson's Snipe Bird": 529,
         "Wilson's Storm-Petrel Bird": 530,
         "Wilson's Warbler Bird": 531,
         "Winter Wren Bird": 532,
         "Wood Duck Bird": 533,
         "Wood Sandpiper Bird": 534,
         "Wood Stork Bird": 535,
         "Wood Thrush Bird": 536,
         "Worm-eating Warbler Bird": 537,
         "Wrentit Bird": 538,
         "Xantus's Hummingbird Bird": 539,
         "Yellow Rail Bird": 540,
         "Yellow Warbler Bird": 541,
         "Yellow-bellied Flycatcher Bird": 542,
         "Yellow-bellied Sapsucker Bird": 543,
         "Yellow-billed Cuckoo Bird": 544,
         "Yellow-billed Loon Bird": 545,
         "Yellow-breasted Chat Bird": 546,
         "Yellow-chevroned Parakeet Bird": 547,
         "Yellow-crowned Night Heron Bird": 548,
         "Yellow-footed Gull Bird": 549,
         "Yellow-green Vireo Bird": 550,
         "Yellow-headed Blackbird Bird": 551,
         "Yellow-headed Parrot Bird": 552,
         "Yellow-rumped Warbler Bird": 553,
         "Yellow-throated Vireo Bird": 554,
         "Yellow-throated Warbler Bird": 555,
         "Zone-tailed Hawk Bird": 556}
         
	return bird_index_list
    
def create_bird_image_links():

	import pandas as pd

	bird_links = {"Abert's Towhee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Abert_s+Towhee+Bird.jpg",
                    "Acorn Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Acorn+Woodpecker+Bird.jpg",
                    "Allen's Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Allen_s+Hummingbird+Bird.jpg",
                    "American Avocet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Avocet+Bird.jpg",
                    "American Bittern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Bittern+Bird.jpg",
                    "American Coot Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Coot+Bird.jpg",
                    "American Crow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Crow+Bird.jpg",
                    "American Dipper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Dipper+Bird.jpg",
                    "American Golden-Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Golden-Plover+Bird.jpg",
                    "American Goldfinch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Goldfinch+Bird.jpg",
                    "American Goshawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Goshawk+Bird.jpg",
                    "American Kestrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Kestrel+Bird.jpg",
                    "American Oystercatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Oystercatcher+Bird.jpg",
                    "American Pipit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Pipit+Bird.jpg",
                    "American Redstart Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Redstart+Bird.jpg",
                    "American Robin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Robin+Bird.jpg",
                    "American Tree Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Tree+Sparrow+Bird.jpg",
                    "American White Pelican Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+White+Pelican+Bird.jpg",
                    "American Wigeon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/American+Wigeon+Bird.jpg",
                    "Ancient Murrelet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ancient+Murrelet+Bird.jpg",
                    "Anhinga Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Anhinga+Bird.jpg",
                    "Anna's Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Anna_s+Hummingbird+Bird.jpg",
                    "Arctic Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Arctic+Tern+Bird.jpg",
                    "Ash-throated Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ash-throated+Flycatcher+Bird.jpg",
                    "Ashy Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ashy+Storm-Petrel+Bird.jpg",
                    "Baird's Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Baird_s+Sandpiper+Bird.jpg",
                    "Baird's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Baird_s+Sparrow+Bird.jpg",
                    "Bald Eagle Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bald+Eagle+Bird.jpg",
                    "Baltimore Oriole Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Baltimore+Oriole+Bird.jpg",
                    "Band-tailed Pigeon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Band-tailed+Pigeon+Bird.jpg",
                    "Bank Swallow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bank+Swallow+Bird.jpg",
                    "Bar-tailed Godwit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bar-tailed+Godwit+Bird.jpg",
                    "Barn Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Barn+Owl+Bird.jpg",
                    "Barn Swallow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Barn+Swallow+Bird.jpg",
                    "Bay-breasted Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bay-breasted+Warbler+Bird.jpg",
                    "Belcher's Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Belcher_s+Gull+Bird.jpg",
                    "Bell's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bell_s+Sparrow+Bird.jpg",
                    "Bell's Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bell_s+Vireo+Bird.jpg",
                    "Belted Kingfisher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Belted+Kingfisher+Bird.jpg",
                    "Bendire's Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bendire_s+Thrasher+Bird.jpg",
                    "Bewick's Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bewick_s+Wren+Bird.jpg",
                    "Black Oystercatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Oystercatcher+Bird.jpg",
                    "Black Phoebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Phoebe+Bird.jpg",
                    "Black Rail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Rail+Bird.jpg",
                    "Black Scoter Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Scoter+Bird.jpg",
                    "Black Skimmer Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Skimmer+Bird.jpg",
                    "Black Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Storm-Petrel+Bird.jpg",
                    "Black Swift Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Swift+Bird.jpg",
                    "Black Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Tern+Bird.jpg",
                    "Black Turnstone Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Turnstone+Bird.jpg",
                    "Black Vulture Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black+Vulture+Bird.jpg",
                    "Black-and-white Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-and-white+Warbler+Bird.jpg",
                    "Black-backed Oriole Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-backed+Oriole+Bird.jpg",
                    "Black-bellied Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-bellied+Plover+Bird.jpg",
                    "Black-chinned Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-chinned+Hummingbird+Bird.jpg",
                    "Black-chinned Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-chinned+Sparrow+Bird.jpg",
                    "Black-crowned Night Heron Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-crowned+Night+Heron+Bird.jpg",
                    "Black-footed Albatross Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-footed+Albatross+Bird.jpg",
                    "Black-headed Grosbeak Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-headed+Grosbeak+Bird.jpg",
                    "Black-headed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-headed+Gull+Bird.jpg",
                    "Black-legged Kittiwake Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-legged+Kittiwake+Bird.jpg",
                    "Black-necked Stilt Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-necked+Stilt+Bird.jpg",
                    "Black-tailed Gnatcatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-tailed+Gnatcatcher+Bird.jpg",
                    "Black-tailed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-tailed+Gull+Bird.jpg",
                    "Black-throated Blue Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-throated+Blue+Warbler+Bird.jpg",
                    "Black-throated Gray Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-throated+Gray+Warbler+Bird.jpg",
                    "Black-throated Green Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-throated+Green+Warbler+Bird.jpg",
                    "Black-throated Magpie-Jay Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-throated+Magpie-Jay+Bird.jpg",
                    "Black-throated Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-throated+Sparrow+Bird.jpg",
                    "Black-vented Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Black-vented+Shearwater+Bird.jpg",
                    "Blackburnian Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blackburnian+Warbler+Bird.jpg",
                    "Blackpoll Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blackpoll+Warbler+Bird.jpg",
                    "Blue Grosbeak Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blue+Grosbeak+Bird.jpg",
                    "Blue-footed Booby Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blue-footed+Booby+Bird.jpg",
                    "Blue-gray Gnatcatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blue-gray+Gnatcatcher+Bird.jpg",
                    "Blue-headed Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blue-headed+Vireo+Bird.jpg",
                    "Blue-throated Mountain-gem Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blue-throated+Mountain-gem+Bird.jpg",
                    "Blue-winged Teal Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blue-winged+Teal+Bird.jpg",
                    "Blue-winged Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Blue-winged+Warbler+Bird.jpg",
                    "Bobolink Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bobolink+Bird.jpg",
                    "Bohemian Waxwing Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bohemian+Waxwing+Bird.jpg",
                    "Bonaparte's Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bonaparte_s+Gull+Bird.jpg",
                    "Brandt's Cormorant Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brandt_s+Cormorant+Bird.jpg",
                    "Brant Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brant+Bird.jpg",
                    "Brewer's Blackbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brewer_s+Blackbird+Bird.jpg",
                    "Brewer's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brewer_s+Sparrow+Bird.jpg",
                    "Bridled Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bridled+Tern+Bird.jpg",
                    "Broad-billed Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Broad-billed+Hummingbird+Bird.jpg",
                    "Broad-tailed Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Broad-tailed+Hummingbird+Bird.jpg",
                    "Broad-winged Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Broad-winged+Hawk+Bird.jpg",
                    "Bronzed Cowbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bronzed+Cowbird+Bird.jpg",
                    "Brown Booby Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brown+Booby+Bird.jpg",
                    "Brown Creeper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brown+Creeper+Bird.jpg",
                    "Brown Pelican Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brown+Pelican+Bird.jpg",
                    "Brown Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brown+Thrasher+Bird.jpg",
                    "Brown-crested Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brown-crested+Flycatcher+Bird.jpg",
                    "Brown-headed Cowbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Brown-headed+Cowbird+Bird.jpg",
                    "Buff-breasted Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Buff-breasted+Sandpiper+Bird.jpg",
                    "Bufflehead Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bufflehead+Bird.jpg",
                    "Buller's Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Buller_s+Shearwater+Bird.jpg",
                    "Bullock's Oriole Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bullock_s+Oriole+Bird.jpg",
                    "Burrowing Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Burrowing+Owl+Bird.jpg",
                    "Bushtit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Bushtit+Bird.jpg",
                    "Cackling Goose Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cackling+Goose+Bird.jpg",
                    "Cactus Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cactus+Wren+Bird.jpg",
                    "California Condor Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/California+Condor+Bird.jpg",
                    "California Gnatcatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/California+Gnatcatcher+Bird.jpg",
                    "California Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/California+Gull+Bird.jpg",
                    "California Quail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/California+Quail+Bird.jpg",
                    "California Scrub-Jay Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/California+Scrub-Jay+Bird.jpg",
                    "California Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/California+Thrasher+Bird.jpg",
                    "California Towhee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/California+Towhee+Bird.jpg",
                    "Calliope Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Calliope+Hummingbird+Bird.jpg",
                    "Canada Goose Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Canada+Goose+Bird.jpg",
                    "Canada Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Canada+Warbler+Bird.jpg",
                    "Canvasback Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Canvasback+Bird.jpg",
                    "Canyon Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Canyon+Wren+Bird.jpg",
                    "Cape May Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cape+May+Warbler+Bird.jpg",
                    "Caspian Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Caspian+Tern+Bird.jpg",
                    "Cassin's Auklet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cassin_s+Auklet+Bird.jpg",
                    "Cassin's Finch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cassin_s+Finch+Bird.jpg",
                    "Cassin's Kingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cassin_s+Kingbird+Bird.jpg",
                    "Cassin's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cassin_s+Sparrow+Bird.jpg",
                    "Cassin's Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cassin_s+Vireo+Bird.jpg",
                    "Cedar Waxwing Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cedar+Waxwing+Bird.jpg",
                    "Cerulean Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cerulean+Warbler+Bird.jpg",
                    "Chestnut-collared Longspur Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Chestnut-collared+Longspur+Bird.jpg",
                    "Chestnut-sided Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Chestnut-sided+Warbler+Bird.jpg",
                    "Chimney Swift Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Chimney+Swift+Bird.jpg",
                    "Chipping Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Chipping+Sparrow+Bird.jpg",
                    "Cinnamon Teal Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cinnamon+Teal+Bird.jpg",
                    "Cinnamon-rumped Seedeater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cinnamon-rumped+Seedeater+Bird.jpg",
                    "Clark's Grebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Clark_s+Grebe+Bird.jpg",
                    "Clark's Nutcracker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Clark_s+Nutcracker+Bird.jpg",
                    "Clay-colored Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Clay-colored+Sparrow+Bird.jpg",
                    "Cliff Swallow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cliff+Swallow+Bird.jpg",
                    "Common Black Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Black+Hawk+Bird.jpg",
                    "Common Gallinule Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Gallinule+Bird.jpg",
                    "Common Goldeneye Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Goldeneye+Bird.jpg",
                    "Common Grackle Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Grackle+Bird.jpg",
                    "Common Ground Dove Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Ground+Dove+Bird.jpg",
                    "Common Loon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Loon+Bird.jpg",
                    "Common Merganser Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Merganser+Bird.jpg",
                    "Common Murre Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Murre+Bird.jpg",
                    "Common Nighthawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Nighthawk+Bird.jpg",
                    "Common Poorwill Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Poorwill+Bird.jpg",
                    "Common Raven Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Raven+Bird.jpg",
                    "Common Redpoll Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Redpoll+Bird.jpg",
                    "Common Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Tern+Bird.jpg",
                    "Common Yellowthroat Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Common+Yellowthroat+Bird.jpg",
                    "Connecticut Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Connecticut+Warbler+Bird.jpg",
                    "Cook's Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cook_s+Petrel+Bird.jpg",
                    "Cooper's Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cooper_s+Hawk+Bird.jpg",
                    "Cory's Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Cory_s+Shearwater+Bird.jpg",
                    "Costa's Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Costa_s+Hummingbird+Bird.jpg",
                    "Craveri's Murrelet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Craveri_s+Murrelet+Bird.jpg",
                    "Crested Caracara Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Crested+Caracara+Bird.jpg",
                    "Crissal Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Crissal+Thrasher+Bird.jpg",
                    "Curlew Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Curlew+Sandpiper+Bird.jpg",
                    "Curve-billed Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Curve-billed+Thrasher+Bird.jpg",
                    "Dark-eyed Junco Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Dark-eyed+Junco+Bird.jpg",
                    "Dickcissel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Dickcissel+Bird.jpg",
                    "Double-crested Cormorant Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Double-crested+Cormorant+Bird.jpg",
                    "Downy Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Downy+Woodpecker+Bird.jpg",
                    "Dunlin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Dunlin+Bird.jpg",
                    "Dusky Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Dusky+Flycatcher+Bird.jpg",
                    "Dusky Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Dusky+Warbler+Bird.jpg",
                    "Dusky-capped Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Dusky-capped+Flycatcher+Bird.jpg",
                    "Eared Grebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eared+Grebe+Bird.jpg",
                    "Eastern Kingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eastern+Kingbird+Bird.jpg",
                    "Eastern Phoebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eastern+Phoebe+Bird.jpg",
                    "Eastern Towhee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eastern+Towhee+Bird.jpg",
                    "Eastern Whip-poor-will Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eastern+Whip-poor-will+Bird.jpg",
                    "Eastern Wood-Pewee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eastern+Wood-Pewee+Bird.jpg",
                    "Elegant Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Elegant+Tern+Bird.jpg",
                    "Eurasian Collared-Dove Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eurasian+Collared-Dove+Bird.jpg",
                    "Eurasian Wigeon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Eurasian+Wigeon+Bird.jpg",
                    "European Starling Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/European+Starling+Bird.jpg",
                    "Evening Grosbeak Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Evening+Grosbeak+Bird.jpg",
                    "Ferruginous Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ferruginous+Hawk+Bird.jpg",
                    "Flammulated Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Flammulated+Owl+Bird.jpg",
                    "Flesh-footed Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Flesh-footed+Shearwater+Bird.jpg",
                    "Fork-tailed Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Fork-tailed+Storm-Petrel+Bird.jpg",
                    "Forster's Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Forster_s+Tern+Bird.jpg",
                    "Fox Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Fox+Sparrow+Bird.jpg",
                    "Franklin's Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Franklin_s+Gull+Bird.jpg",
                    "Fulvous Whistling-Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Fulvous+Whistling-Duck+Bird.jpg",
                    "Gadwall Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gadwall+Bird.jpg",
                    "Gambel's Quail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gambel_s+Quail+Bird.jpg",
                    "Gila Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gila+Woodpecker+Bird.jpg",
                    "Glaucous Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Glaucous+Gull+Bird.jpg",
                    "Glaucous-winged Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Glaucous-winged+Gull+Bird.jpg",
                    "Glossy Ibis Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Glossy+Ibis+Bird.jpg",
                    "Golden Eagle Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Golden+Eagle+Bird.jpg",
                    "Golden-crowned Kinglet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Golden-crowned+Kinglet+Bird.jpg",
                    "Golden-crowned Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Golden-crowned+Sparrow+Bird.jpg",
                    "Golden-winged Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Golden-winged+Warbler+Bird.jpg",
                    "Grace's Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Grace_s+Warbler+Bird.jpg",
                    "Grasshopper Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Grasshopper+Sparrow+Bird.jpg",
                    "Gray Catbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray+Catbird+Bird.jpg",
                    "Gray Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray+Flycatcher+Bird.jpg",
                    "Gray Silky-flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray+Silky-flycatcher+Bird.jpg",
                    "Gray Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray+Thrasher+Bird.jpg",
                    "Gray Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray+Vireo+Bird.jpg",
                    "Gray-cheeked Thrush Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray-cheeked+Thrush+Bird.jpg",
                    "Gray-faced Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray-faced+Petrel+Bird.jpg",
                    "Gray-tailed Tattler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gray-tailed+Tattler+Bird.jpg",
                    "Great Blue Heron Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Great+Blue+Heron+Bird.jpg",
                    "Great Crested Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Great+Crested+Flycatcher+Bird.jpg",
                    "Great Egret Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Great+Egret+Bird.jpg",
                    "Great Horned Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Great+Horned+Owl+Bird.jpg",
                    "Great Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Great+Shearwater+Bird.jpg",
                    "Great-tailed Grackle Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Great-tailed+Grackle+Bird.jpg",
                    "Greater Pewee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Greater+Pewee+Bird.jpg",
                    "Greater Roadrunner Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Greater+Roadrunner+Bird.jpg",
                    "Greater Scaup Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Greater+Scaup+Bird.jpg",
                    "Greater White-fronted Goose Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Greater+White-fronted+Goose+Bird.jpg",
                    "Greater Yellowlegs Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Greater+Yellowlegs+Bird.jpg",
                    "Green Heron Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Green+Heron+Bird.jpg",
                    "Green-tailed Towhee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Green-tailed+Towhee+Bird.jpg",
                    "Green-winged Teal Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Green-winged+Teal+Bird.jpg",
                    "Groove-billed Ani Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Groove-billed+Ani+Bird.jpg",
                    "Guadalupe Murrelet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Guadalupe+Murrelet+Bird.jpg",
                    "Gull-billed Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Gull-billed+Tern+Bird.jpg",
                    "Hairy Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hairy+Woodpecker+Bird.jpg",
                    "Hammond's Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hammond_s+Flycatcher+Bird.jpg",
                    "Harlequin Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Harlequin+Duck+Bird.jpg",
                    "Harris's Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Harris_s+Hawk+Bird.jpg",
                    "Harris's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Harris_s+Sparrow+Bird.jpg",
                    "Heermann's Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Heermann_s+Gull+Bird.jpg",
                    "Hepatic Tanager Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hepatic+Tanager+Bird.jpg",
                    "Hermit Thrush Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hermit+Thrush+Bird.jpg",
                    "Hermit Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hermit+Warbler+Bird.jpg",
                    "Herring Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Herring+Gull+Bird.jpg",
                    "Hooded Merganser Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hooded+Merganser+Bird.jpg",
                    "Hooded Oriole Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hooded+Oriole+Bird.jpg",
                    "Hooded Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hooded+Warbler+Bird.jpg",
                    "Horned Grebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Horned+Grebe+Bird.jpg",
                    "Horned Lark Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Horned+Lark+Bird.jpg",
                    "Horned Puffin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Horned+Puffin+Bird.jpg",
                    "House Finch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/House+Finch+Bird.jpg",
                    "House Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/House+Sparrow+Bird.jpg",
                    "House Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/House+Wren+Bird.jpg",
                    "Hudsonian Godwit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hudsonian+Godwit+Bird.jpg",
                    "Hutton's Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Hutton_s+Vireo+Bird.jpg",
                    "Iceland Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Iceland+Gull+Bird.jpg",
                    "Inca Dove Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Inca+Dove+Bird.jpg",
                    "Indigo Bunting Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Indigo+Bunting+Bird.jpg",
                    "Kentucky Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Kentucky+Warbler+Bird.jpg",
                    "Killdeer Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Killdeer+Bird.jpg",
                    "King Eider Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/King+Eider+Bird.jpg",
                    "Kittlitz's Murrelet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Kittlitz_s+Murrelet+Bird.jpg",
                    "Ladder-backed Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ladder-backed+Woodpecker+Bird.jpg",
                    "Lapland Longspur Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lapland+Longspur+Bird.jpg",
                    "Lark Bunting Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lark+Bunting+Bird.jpg",
                    "Lark Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lark+Sparrow+Bird.jpg",
                    "Laughing Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Laughing+Gull+Bird.jpg",
                    "Lawrence's Goldfinch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lawrence_s+Goldfinch+Bird.jpg",
                    "Laysan Albatross Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Laysan+Albatross+Bird.jpg",
                    "Lazuli Bunting Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lazuli+Bunting+Bird.jpg",
                    "LeConte's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/LeConte_s+Sparrow+Bird.jpg",
                    "LeConte's Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/LeConte_s+Thrasher+Bird.jpg",
                    "Leach's Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Leach_s+Storm-Petrel+Bird.jpg",
                    "Least Bittern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Least+Bittern+Bird.jpg",
                    "Least Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Least+Flycatcher+Bird.jpg",
                    "Least Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Least+Sandpiper+Bird.jpg",
                    "Least Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Least+Storm-Petrel+Bird.jpg",
                    "Least Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Least+Tern+Bird.jpg",
                    "Lesser Black-backed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lesser+Black-backed+Gull+Bird.jpg",
                    "Lesser Goldfinch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lesser+Goldfinch+Bird.jpg",
                    "Lesser Nighthawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lesser+Nighthawk+Bird.jpg",
                    "Lesser Scaup Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lesser+Scaup+Bird.jpg",
                    "Lesser Yellowlegs Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lesser+Yellowlegs+Bird.jpg",
                    "Lewis's Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lewis_s+Woodpecker+Bird.jpg",
                    "Lilac-crowned Parrot Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lilac-crowned+Parrot+Bird.jpg",
                    "Lincoln's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lincoln_s+Sparrow+Bird.jpg",
                    "Little Blue Heron Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Little+Blue+Heron+Bird.jpg",
                    "Little Bunting Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Little+Bunting+Bird.jpg",
                    "Little Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Little+Gull+Bird.jpg",
                    "Little Stint Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Little+Stint+Bird.jpg",
                    "Loggerhead Shrike Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Loggerhead+Shrike+Bird.jpg",
                    "Long-billed Curlew Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Long-billed+Curlew+Bird.jpg",
                    "Long-billed Dowitcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Long-billed+Dowitcher+Bird.jpg",
                    "Long-eared Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Long-eared+Owl+Bird.jpg",
                    "Long-tailed Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Long-tailed+Duck+Bird.jpg",
                    "Long-tailed Jaeger Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Long-tailed+Jaeger+Bird.jpg",
                    "Louisiana Waterthrush Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Louisiana+Waterthrush+Bird.jpg",
                    "Lucy's Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Lucy_s+Warbler+Bird.jpg",
                    "MacGillivray's Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/MacGillivray_s+Warbler+Bird.jpg",
                    "Magnificent Frigatebird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Magnificent+Frigatebird+Bird.jpg",
                    "Magnolia Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Magnolia+Warbler+Bird.jpg",
                    "Mallard Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mallard+Bird.jpg",
                    "Mandarin Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mandarin+Duck+Bird.jpg",
                    "Manx Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Manx+Shearwater+Bird.jpg",
                    "Marbled Godwit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Marbled+Godwit+Bird.jpg",
                    "Marbled Murrelet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Marbled+Murrelet+Bird.jpg",
                    "Marsh Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Marsh+Wren+Bird.jpg",
                    "Masked Booby Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Masked+Booby+Bird.jpg",
                    "Merlin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Merlin+Bird.jpg",
                    "Mexican Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mexican+Duck+Bird.jpg",
                    "Mexican Whip-poor-will Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mexican+Whip-poor-will+Bird.jpg",
                    "Mississippi Kite Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mississippi+Kite+Bird.jpg",
                    "Mitred Parakeet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mitred+Parakeet+Bird.jpg",
                    "Monk Parakeet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Monk+Parakeet+Bird.jpg",
                    "Mottled Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mottled+Petrel+Bird.jpg",
                    "Mountain Bluebird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mountain+Bluebird+Bird.jpg",
                    "Mountain Chickadee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mountain+Chickadee+Bird.jpg",
                    "Mountain Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mountain+Plover+Bird.jpg",
                    "Mountain Quail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mountain+Quail+Bird.jpg",
                    "Mourning Dove Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mourning+Dove+Bird.jpg",
                    "Mourning Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Mourning+Warbler+Bird.jpg",
                    "Nashville Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Nashville+Warbler+Bird.jpg",
                    "Nazca Booby Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Nazca+Booby+Bird.jpg",
                    "Nelson's Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Nelson_s+Sparrow+Bird.jpg",
                    "Neotropic Cormorant Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Neotropic+Cormorant+Bird.jpg",
                    "Newell's Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Newell_s+Shearwater+Bird.jpg",
                    "Northern Flicker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Flicker+Bird.jpg",
                    "Northern Fulmar Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Fulmar+Bird.jpg",
                    "Northern Harrier Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Harrier+Bird.jpg",
                    "Northern Mockingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Mockingbird+Bird.jpg",
                    "Northern Parula Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Parula+Bird.jpg",
                    "Northern Pintail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Pintail+Bird.jpg",
                    "Northern Pygmy-Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Pygmy-Owl+Bird.jpg",
                    "Northern Red Bishop Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Red+Bishop+Bird.jpg",
                    "Northern Rough-winged Swallow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Rough-winged+Swallow+Bird.jpg",
                    "Northern Saw-whet Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Saw-whet+Owl+Bird.jpg",
                    "Northern Shoveler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Shoveler+Bird.jpg",
                    "Northern Waterthrush Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Waterthrush+Bird.jpg",
                    "Northern Wheatear Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Northern+Wheatear+Bird.jpg",
                    "Nuttall's Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Nuttall_s+Woodpecker+Bird.jpg",
                    "Oak Titmouse Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Oak+Titmouse+Bird.jpg",
                    "Olive-sided Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Olive-sided+Flycatcher+Bird.jpg",
                    "Orange-crowned Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Orange-crowned+Warbler+Bird.jpg",
                    "Orchard Oriole Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Orchard+Oriole+Bird.jpg",
                    "Osprey Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Osprey+Bird.jpg",
                    "Ovenbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ovenbird+Bird.jpg",
                    "Pacific Golden-Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pacific+Golden-Plover+Bird.jpg",
                    "Pacific Loon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pacific+Loon+Bird.jpg",
                    "Pacific Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pacific+Wren+Bird.jpg",
                    "Painted Bunting Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Painted+Bunting+Bird.jpg",
                    "Painted Redstart Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Painted+Redstart+Bird.jpg",
                    "Palm Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Palm+Warbler+Bird.jpg",
                    "Parakeet Auklet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Parakeet+Auklet+Bird.jpg",
                    "Parasitic Jaeger Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Parasitic+Jaeger+Bird.jpg",
                    "Pectoral Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pectoral+Sandpiper+Bird.jpg",
                    "Pelagic Cormorant Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pelagic+Cormorant+Bird.jpg",
                    "Peregrine Falcon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Peregrine+Falcon+Bird.jpg",
                    "Phainopepla Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Phainopepla+Bird.jpg",
                    "Philadelphia Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Philadelphia+Vireo+Bird.jpg",
                    "Pied-billed Grebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pied-billed+Grebe+Bird.jpg",
                    "Pigeon Guillemot Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pigeon+Guillemot+Bird.jpg",
                    "Pine Siskin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pine+Siskin+Bird.jpg",
                    "Pine Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pine+Warbler+Bird.jpg",
                    "Pink-footed Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pink-footed+Shearwater+Bird.jpg",
                    "Pinyon Jay Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pinyon+Jay+Bird.jpg",
                    "Plumbeous Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Plumbeous+Vireo+Bird.jpg",
                    "Pomarine Jaeger Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pomarine+Jaeger+Bird.jpg",
                    "Prairie Falcon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Prairie+Falcon+Bird.jpg",
                    "Prairie Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Prairie+Warbler+Bird.jpg",
                    "Prothonotary Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Prothonotary+Warbler+Bird.jpg",
                    "Purple Finch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Purple+Finch+Bird.jpg",
                    "Purple Gallinule Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Purple+Gallinule+Bird.jpg",
                    "Purple Martin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Purple+Martin+Bird.jpg",
                    "Pygmy Nuthatch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pygmy+Nuthatch+Bird.jpg",
                    "Pyrrhuloxia Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Pyrrhuloxia+Bird.jpg",
                    "Red Crossbill Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red+Crossbill+Bird.jpg",
                    "Red Knot Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red+Knot+Bird.jpg",
                    "Red Phalarope Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red+Phalarope+Bird.jpg",
                    "Red-billed Tropicbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-billed+Tropicbird+Bird.jpg",
                    "Red-breasted Merganser Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-breasted+Merganser+Bird.jpg",
                    "Red-breasted Nuthatch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-breasted+Nuthatch+Bird.jpg",
                    "Red-breasted Sapsucker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-breasted+Sapsucker+Bird.jpg",
                    "Red-crowned Parrot Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-crowned+Parrot+Bird.jpg",
                    "Red-eyed Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-eyed+Vireo+Bird.jpg",
                    "Red-faced Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-faced+Warbler+Bird.jpg",
                    "Red-footed Booby Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-footed+Booby+Bird.jpg",
                    "Red-lored Parrot Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-lored+Parrot+Bird.jpg",
                    "Red-masked Parakeet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-masked+Parakeet+Bird.jpg",
                    "Red-naped Sapsucker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-naped+Sapsucker+Bird.jpg",
                    "Red-necked Grebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-necked+Grebe+Bird.jpg",
                    "Red-necked Phalarope Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-necked+Phalarope+Bird.jpg",
                    "Red-necked Stint Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-necked+Stint+Bird.jpg",
                    "Red-shouldered Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-shouldered+Hawk+Bird.jpg",
                    "Red-tailed Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-tailed+Hawk+Bird.jpg",
                    "Red-tailed Tropicbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-tailed+Tropicbird+Bird.jpg",
                    "Red-throated Loon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-throated+Loon+Bird.jpg",
                    "Red-throated Pipit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-throated+Pipit+Bird.jpg",
                    "Red-whiskered Bulbul Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-whiskered+Bulbul+Bird.jpg",
                    "Red-winged Blackbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Red-winged+Blackbird+Bird.jpg",
                    "Reddish Egret Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Reddish+Egret+Bird.jpg",
                    "Redhead Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Redhead+Bird.jpg",
                    "Rhinoceros Auklet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rhinoceros+Auklet+Bird.jpg",
                    "Ridgway's Rail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ridgway_s+Rail+Bird.jpg",
                    "Ring-billed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ring-billed+Gull+Bird.jpg",
                    "Ring-necked Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ring-necked+Duck+Bird.jpg",
                    "Ring-necked Pheasant Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ring-necked+Pheasant+Bird.jpg",
                    "Rivoli's Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rivoli_s+Hummingbird+Bird.jpg",
                    "Rock Pigeon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rock+Pigeon+Bird.jpg",
                    "Rock Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rock+Wren+Bird.jpg",
                    "Rose-breasted Grosbeak Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rose-breasted+Grosbeak+Bird.jpg",
                    "Rose-ringed Parakeet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rose-ringed+Parakeet+Bird.jpg",
                    "Roseate Spoonbill Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Roseate+Spoonbill+Bird.jpg",
                    "Ross's Goose Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ross_s+Goose+Bird.jpg",
                    "Rough-legged Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rough-legged+Hawk+Bird.jpg",
                    "Royal Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Royal+Tern+Bird.jpg",
                    "Ruby-crowned Kinglet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ruby-crowned+Kinglet+Bird.jpg",
                    "Ruddy Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ruddy+Duck+Bird.jpg",
                    "Ruddy Ground Dove Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ruddy+Ground+Dove+Bird.jpg",
                    "Ruddy Turnstone Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ruddy+Turnstone+Bird.jpg",
                    "Ruff Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Ruff+Bird.jpg",
                    "Rufous Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rufous+Hummingbird+Bird.jpg",
                    "Rufous-backed Robin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rufous-backed+Robin+Bird.jpg",
                    "Rufous-crowned Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rufous-crowned+Sparrow+Bird.jpg",
                    "Rusty Blackbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Rusty+Blackbird+Bird.jpg",
                    "Sabine's Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sabine_s+Gull+Bird.jpg",
                    "Sage Thrasher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sage+Thrasher+Bird.jpg",
                    "Sagebrush Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sagebrush+Sparrow+Bird.jpg",
                    "Sanderling Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sanderling+Bird.jpg",
                    "Sandhill Crane Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sandhill+Crane+Bird.jpg",
                    "Sandwich Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sandwich+Tern+Bird.jpg",
                    "Savannah Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Savannah+Sparrow+Bird.jpg",
                    "Say's Phoebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Say_s+Phoebe+Bird.jpg",
                    "Scaly-breasted Munia Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Scaly-breasted+Munia+Bird.jpg",
                    "Scarlet Tanager Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Scarlet+Tanager+Bird.jpg",
                    "Scissor-tailed Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Scissor-tailed+Flycatcher+Bird.jpg",
                    "Scott's Oriole Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Scott_s+Oriole+Bird.jpg",
                    "Scripps's Murrelet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Scripps_s+Murrelet+Bird.jpg",
                    "Semipalmated Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Semipalmated+Plover+Bird.jpg",
                    "Semipalmated Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Semipalmated+Sandpiper+Bird.jpg",
                    "Sharp-shinned Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sharp-shinned+Hawk+Bird.jpg",
                    "Sharp-tailed Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sharp-tailed+Sandpiper+Bird.jpg",
                    "Short-billed Dowitcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Short-billed+Dowitcher+Bird.jpg",
                    "Short-billed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Short-billed+Gull+Bird.jpg",
                    "Short-eared Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Short-eared+Owl+Bird.jpg",
                    "Short-tailed Albatross Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Short-tailed+Albatross+Bird.jpg",
                    "Short-tailed Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Short-tailed+Shearwater+Bird.jpg",
                    "Siberian Sand-Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Siberian+Sand-Plover+Bird.jpg",
                    "Slaty-backed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Slaty-backed+Gull+Bird.jpg",
                    "Snow Bunting Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Snow+Bunting+Bird.jpg",
                    "Snow Goose Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Snow+Goose+Bird.jpg",
                    "Snowy Egret Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Snowy+Egret+Bird.jpg",
                    "Snowy Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Snowy+Plover+Bird.jpg",
                    "Solitary Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Solitary+Sandpiper+Bird.jpg",
                    "Song Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Song+Sparrow+Bird.jpg",
                    "Sooty Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sooty+Shearwater+Bird.jpg",
                    "Sooty Tern Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sooty+Tern+Bird.jpg",
                    "Sora Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sora+Bird.jpg",
                    "South Polar Skua Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/South+Polar+Skua+Bird.jpg",
                    "Spotted Dove Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Spotted+Dove+Bird.jpg",
                    "Spotted Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Spotted+Owl+Bird.jpg",
                    "Spotted Redshank Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Spotted+Redshank+Bird.jpg",
                    "Spotted Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Spotted+Sandpiper+Bird.jpg",
                    "Spotted Towhee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Spotted+Towhee+Bird.jpg",
                    "Sprague's Pipit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sprague_s+Pipit+Bird.jpg",
                    "Stejneger's Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Stejneger_s+Petrel+Bird.jpg",
                    "Steller's Jay Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Steller_s+Jay+Bird.jpg",
                    "Stilt Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Stilt+Sandpiper+Bird.jpg",
                    "Streak-backed Oriole Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Streak-backed+Oriole+Bird.jpg",
                    "Streaked Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Streaked+Shearwater+Bird.jpg",
                    "Sulphur-bellied Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Sulphur-bellied+Flycatcher+Bird.jpg",
                    "Summer Tanager Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Summer+Tanager+Bird.jpg",
                    "Surf Scoter Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Surf+Scoter+Bird.jpg",
                    "Surfbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Surfbird+Bird.jpg",
                    "Swainson's Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Swainson_s+Hawk+Bird.jpg",
                    "Swainson's Thrush Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Swainson_s+Thrush+Bird.jpg",
                    "Swallow-tailed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Swallow-tailed+Gull+Bird.jpg",
                    "Swallow-tailed Kite Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Swallow-tailed+Kite+Bird.jpg",
                    "Swamp Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Swamp+Sparrow+Bird.jpg",
                    "Swinhoe's White-eye Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Swinhoe_s+White-eye+Bird.jpg",
                    "Tennessee Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tennessee+Warbler+Bird.jpg",
                    "Thick-billed Kingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Thick-billed+Kingbird+Bird.jpg",
                    "Thick-billed Longspur Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Thick-billed+Longspur+Bird.jpg",
                    "Townsend's Solitaire Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Townsend_s+Solitaire+Bird.jpg",
                    "Townsend's Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Townsend_s+Storm-Petrel+Bird.jpg",
                    "Townsend's Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Townsend_s+Warbler+Bird.jpg",
                    "Tree Swallow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tree+Swallow+Bird.jpg",
                    "Tricolored Blackbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tricolored+Blackbird+Bird.jpg",
                    "Tricolored Heron Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tricolored+Heron+Bird.jpg",
                    "Tropical Kingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tropical+Kingbird+Bird.jpg",
                    "Tufted Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tufted+Duck+Bird.jpg",
                    "Tufted Puffin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tufted+Puffin+Bird.jpg",
                    "Tundra Swan Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Tundra+Swan+Bird.jpg",
                    "Turkey Vulture Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Turkey+Vulture+Bird.jpg",
                    "Upland Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Upland+Sandpiper+Bird.jpg",
                    "Varied Bunting Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Varied+Bunting+Bird.jpg",
                    "Varied Thrush Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Varied+Thrush+Bird.jpg",
                    "Vaux's Swift Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Vaux_s+Swift+Bird.jpg",
                    "Verdin Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Verdin+Bird.jpg",
                    "Vermilion Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Vermilion+Flycatcher+Bird.jpg",
                    "Vesper Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Vesper+Sparrow+Bird.jpg",
                    "Violet-crowned Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Violet-crowned+Hummingbird+Bird.jpg",
                    "Violet-green Swallow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Violet-green+Swallow+Bird.jpg",
                    "Virginia Rail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Virginia+Rail+Bird.jpg",
                    "Virginia's Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Virginia_s+Warbler+Bird.jpg",
                    "Wandering Tattler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wandering+Tattler+Bird.jpg",
                    "Warbling Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Warbling+Vireo+Bird.jpg",
                    "Warbling White-eye Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Warbling+White-eye+Bird.jpg",
                    "Wedge-rumped Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wedge-rumped+Storm-Petrel+Bird.jpg",
                    "Wedge-tailed Shearwater Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wedge-tailed+Shearwater+Bird.jpg",
                    "Western Bluebird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Bluebird+Bird.jpg",
                    "Western Cattle Egret Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Cattle+Egret+Bird.jpg",
                    "Western Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Flycatcher+Bird.jpg",
                    "Western Grebe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Grebe+Bird.jpg",
                    "Western Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Gull+Bird.jpg",
                    "Western Kingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Kingbird+Bird.jpg",
                    "Western Meadowlark Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Meadowlark+Bird.jpg",
                    "Western Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Sandpiper+Bird.jpg",
                    "Western Screech-Owl Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Screech-Owl+Bird.jpg",
                    "Western Tanager Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Tanager+Bird.jpg",
                    "Western Wood-Pewee Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Western+Wood-Pewee+Bird.jpg",
                    "Whimbrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Whimbrel+Bird.jpg",
                    "White Ibis Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White+Ibis+Bird.jpg",
                    "White Wagtail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White+Wagtail+Bird.jpg",
                    "White-breasted Nuthatch Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-breasted+Nuthatch+Bird.jpg",
                    "White-crowned Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-crowned+Sparrow+Bird.jpg",
                    "White-eyed Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-eyed+Vireo+Bird.jpg",
                    "White-faced Ibis Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-faced+Ibis+Bird.jpg",
                    "White-headed Woodpecker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-headed+Woodpecker+Bird.jpg",
                    "White-tailed Kite Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-tailed+Kite+Bird.jpg",
                    "White-throated Sparrow Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-throated+Sparrow+Bird.jpg",
                    "White-throated Swift Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-throated+Swift+Bird.jpg",
                    "White-winged Dove Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-winged+Dove+Bird.jpg",
                    "White-winged Scoter Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/White-winged+Scoter+Bird.jpg",
                    "Wild Turkey Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wild+Turkey+Bird.jpg",
                    "Willet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Willet+Bird.jpg",
                    "Williamson's Sapsucker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Williamson_s+Sapsucker+Bird.jpg",
                    "Willow Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Willow+Flycatcher+Bird.jpg",
                    "Wilson's Phalarope Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wilson_s+Phalarope+Bird.jpg",
                    "Wilson's Plover Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wilson_s+Plover+Bird.jpg",
                    "Wilson's Snipe Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wilson_s+Snipe+Bird.jpg",
                    "Wilson's Storm-Petrel Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wilson_s+Storm-Petrel+Bird.jpg",
                    "Wilson's Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wilson_s+Warbler+Bird.jpg",
                    "Winter Wren Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Winter+Wren+Bird.jpg",
                    "Wood Duck Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wood+Duck+Bird.jpg",
                    "Wood Sandpiper Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wood+Sandpiper+Bird.jpg",
                    "Wood Stork Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wood+Stork+Bird.jpg",
                    "Wood Thrush Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wood+Thrush+Bird.jpg",
                    "Worm-eating Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Worm-eating+Warbler+Bird.jpg",
                    "Wrentit Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Wrentit+Bird.jpg",
                    "Xantus's Hummingbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Xantus_s+Hummingbird+Bird.jpg",
                    "Yellow Rail Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow+Rail+Bird.jpg",
                    "Yellow Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow+Warbler+Bird.jpg",
                    "Yellow-bellied Flycatcher Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-bellied+Flycatcher+Bird.jpg",
                    "Yellow-bellied Sapsucker Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-bellied+Sapsucker+Bird.jpg",
                    "Yellow-billed Cuckoo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-billed+Cuckoo+Bird.jpg",
                    "Yellow-billed Loon Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-billed+Loon+Bird.jpg",
                    "Yellow-breasted Chat Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-breasted+Chat+Bird.jpg",
                    "Yellow-chevroned Parakeet Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-chevroned+Parakeet+Bird.jpg",
                    "Yellow-crowned Night Heron Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-crowned+Night+Heron+Bird.jpg",
                    "Yellow-footed Gull Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-footed+Gull+Bird.jpg",
                    "Yellow-green Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-green+Vireo+Bird.jpg",
                    "Yellow-headed Blackbird Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-headed+Blackbird+Bird.jpg",
                    "Yellow-headed Parrot Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-headed+Parrot+Bird.jpg",
                    "Yellow-rumped Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-rumped+Warbler+Bird.jpg",
                    "Yellow-throated Vireo Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-throated+Vireo+Bird.jpg",
                    "Yellow-throated Warbler Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Yellow-throated+Warbler+Bird.jpg",
                    "Zone-tailed Hawk Bird":"https://ab4bucket.s3.us-east-2.amazonaws.com/Zone-tailed+Hawk+Bird.jpg"}

	bird_links_df = pd.DataFrame.from_dict(bird_links, orient='index').reset_index()
	bird_links_df.columns = ['Species', 'Link']

	return bird_links_df
    
    
    
    
    
    